import img1 from '../assets/images/1.png'
import img2 from '../assets/images/2.png'
import img3 from '../assets/images/3.png'
import img4 from '../assets/images/4.png'
import img5 from '../assets/images/5.png'
import img6 from '../assets/images/6.png'
import img7 from '../assets/images/7.png'
import img8 from '../assets/images/8.png'
import img9 from '../assets/images/9.png'
import img10 from '../assets/images/10.png'

const images = [
  { src: img1, desc: 'A dreamy AI-generated mountain landscape during sunset.' },
  { src: img2, desc: 'A futuristic cyberpunk cityscape generated by an AI model.' },
  { src: img3, desc: 'Surreal dreamlike artwork with melting clocks and floating islands.' },
  { src: img4, desc: 'A humanoid robot portrait imagined by a generative neural network.' },
  { src: img5, desc: 'A dense magical forest rendered entirely by AI.' },
  { src: img6, desc: 'An abstract explosion of color and shape designed by AI.' },
  { src: img7, desc: 'A tranquil AI-generated ocean view with glowing jellyfish.' },
  { src: img8, desc: "A real photo transformed into Van Gogh's painting style by AI." },
  { src: img9, desc: 'A vivid depiction of a nebula and stars imagined by machine learning.' },
  { src: img10, desc: 'A fantasy animal hybrid created using a diffusion model.' }
]

export default function Gallery() {
  return (
    <div className="page">
      <h1>AI Art Gallery</h1>
      {images.map((img, i) => (
        <div key={i} className="image-box">
          <img src={img.src} alt={img.desc} />
          <p>{img.desc}</p>
        </div>
      ))}
    </div>
  )
}
