const images = [
    {
      src: '/images/1.png',
      desc: 'A dreamy AI-generated mountain landscape during sunset.'
    },
    {
      src: '/images/2.png',
      desc: 'A futuristic cyberpunk cityscape generated by an AI model.'
    },
    {
      src: '/images/3.png',
      desc: 'Surreal dreamlike artwork with melting clocks and floating islands.'
    },
    {
      src: '/images/4.png',
      desc: 'A humanoid robot portrait imagined by a generative neural network.'
    },
    {
      src: '/images/5.png',
      desc: 'A dense magical forest rendered entirely by AI.'
    },
    {
      src: '/images/6.png',
      desc: 'An abstract explosion of color and shape designed by AI.'
    },
    {
      src: '/images/7.png',
      desc: 'A tranquil AI-generated ocean view with glowing jellyfish.'
    },
    {
      src: '/images/8.png',
      desc: 'A real photo transformed into Van Gogh’s painting style by AI.'
    },
    {
      src: '/images/9.png',
      desc: 'A vivid depiction of a nebula and stars imagined by machine learning.'
    },
    {
      src: '/images/10.png',
      desc: 'A fantasy animal hybrid created using a diffusion model.'
    }
  ]
  
  
  export default function Gallery() {
    return (
      <div className="page">
        <h1>AI Art Gallery</h1>
        {images.map((img, i) => (
          <div key={i} className="image-box">
            <img src={img.src} alt={img.desc} />
            <p>{img.desc}</p>
          </div>
        ))}
      </div>
    )
  }
  